### ISSUE TITLE
gpg is required but missing from base debian 12 cloud image

### ISSUE THREAD

**Issue by si458** [MailCleaner/MailCleaner-Next#35]
if you follow the steps to setup the new mailcleaner on a base debain 12 cloud image, it doesnt include GPG by default!
https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
so you must install it first!
could you add this to the script or docs?

```
root@mailcleaner:/usr/mailcleaner# debian-bootstrap/install.sh
Bootstrapping MailCleaner installation
MailCleaner requires the Debian 'non-free' repository to function. Do you consent to enabling this repo? [y/N]: y
 Checking non-free repo *

debian-bootstrap/install.sh: line 102: gpg: command not found
debian-bootstrap/install.sh: line 109: gpg: command not found
debian-bootstrap/install.sh: line 116: gpg: command not found
deb [signed-by=/etc/apt/keyrings/obs-home-voegelas.gpg] https://download.opensuse.org/repositories/home:/voegelas/Debian_12/ ./
Clearing APT cache *
Updating APT repos...W: GPG error: https://download.docker.com/linux/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/debian bookworm InRelease' is not signed.
W: GPG error: https://download.opensuse.org/repositories/home:/voegelas/Debian_12 ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 513F9EC6598C6214
E: The repository 'https://download.opensuse.org/repositories/home:/voegelas/Debian_12 ./ InRelease' is not signed.
W: GPG error: http://cdnmcpool.mailcleaner.net bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 14BDC38F38BE9807
E: The repository 'http://cdnmcpool.mailcleaner.net bookworm InRelease' is not signed.
 *
```

**Comment by JohnMertz** [comment]
Thanks!

This should be resolved by: https://github.com/MailCleaner/MailCleaner-Next/pull/40

This simply installs `gpg` if not already installed, before adding the repos/importing the keys.

I think it should be okay to remove `gpg` from the guide again, but I have not actually tested this patch yet.

So far, I'm doing all my testing with the NetInstall image with QEMU, so it is good to have someone test on a different target. I'm a bit busy with some behind-the-scenes stuff this week, so if you have the time to check that this patch worked and want to close the ticket, that's great. Otherwise I'll probably look into setting up a test environment with the Cloud image next week.

**Comment by si458** [comment]
Hi
Thanks for that, no that didn't work shows an error
```
Checking/adding extra repositories...
debian-bootstrap/install.sh: line 103: !grep: command not found
```
