### ISSUE TITLE
/usr/mailcleaner/etc/mailcleaner/patchlevel.def is missing

### ISSUE THREAD

**Issue by uncltom** [MailCleaner/MailCleaner-Next#44]
I created a file with the number 1 in it and SNMP started working.

**Comment by uncltom** [comment]
I added the file in a pulll request.

**Comment by JohnMertz** [comment]
Thanks for pointing this out. In the current release the patch level is defined by the most recent update script. Since this version currently has no updates, it does not exist.

I don't want to track that file in Git, since it will cause conflicts when actual updates arrive. Instead this should be worked around in the SNMP start script/dumper. I'll look into a proper patch tomorrow.
